theme: minima
title: Serg's blog
author: Sergiu Radu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The amazing journey continues with the marvellous blog writing. Enjoy!
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
